### PR TITLE
Add debug line support

### PR DESCRIPTION
**Pull request by henopied**
This pull should add support for the debug line that can be sent by the server.

### CODE REVIEW

**Comment by pulviscriptor** [comment]
Hi.
Thank you for your great job! But i have few requests.
Your editor deleted spaces before new line characters. Without spaces markdown will think there is no new lines. Bring spaces back please.
And do not change `ws` version please. It was tested with 0.7.1 and worked so lets leave "0.7.1 or higher"

**Comment by henopied** [comment]
The markdown looks fine to me without the spaces and I see no harm in changing the ws version unless there is any large api change that broke it (I will need to test this but it seemed fine)

**Comment by pulviscriptor** [comment]
Github changed behavior of markdown, but editor i use uses original [specification](https://daringfireball.net/projects/markdown/syntax#p). I need those spaces.
>When you do want to insert a \<br /\> break tag using Markdown, you end a line with two or more spaces, then type return. 

And about version, i need it to tell peoples that `0.7.1` is supported too. If there will be `0.8.1` that will mean `0.7.1` is not supported/tested. I don't know whats changed in `0.8.1`, maybe someone will like to use `0.7.1` but will be not able because package will request `0.8.1`.
I want to keep `0.7.1`.
Looks like you can just push changes to your fork and they will change this PR without creating new PR
https://stackoverflow.com/questions/16748115/how-to-modify-github-pull-request

**Comment by pulviscriptor** [comment]
Turns out that updating `ws` was correct thing to do.
https://github.com/pulviscriptor/agario-client/issues/55#issuecomment-171488829

**Pull request merged**
