### PR TITLE
In browser support

### PR DESCRIPTION
**Pull request by GeoffreyFrogeye**
Do **not** merge until the following list is filled.

This PR is in fact a combination of two features, the first one is the support for `agario-client.js` for the browser, and [a fully featured graphical client](http://i.imgur.com/vGLXdN0.png) in browser. I had some issues with making the client cross-compatible (it only works in the browser for now), and I wanted to discuss the way to go before considering this complete. And in the meanwhile I developed this graphical client on the same branch, that's why this PR contains two features, my bad :wink:.

Here's the TODO list:
- [x] Make the client work in the browser
- [ ] Make the client cross-platform
- [ ] Add some documentation

I was thinking about using [some hack](http://stackoverflow.com/questions/4224606/how-to-check-whether-a-script-is-running-under-node-js) to detect which platform is running `agario-client.js` and then load the libraries accordingly, are you okay with that ?

### CODE REVIEW

**Comment by pulviscriptor** [comment]
Hi.
I think due to lack of my English knowledge i can't fully understand what you're trying to do.
Copying `EventEmitter.prototype` via `for` is good, it will bring compatibility with the [documentation](https://nodejs.org/api/events.html).
`Client.color` fix part is awesome. I didn't tested it at all and now i see that it was completely broken.
But can you please explain why do you want to support web browsers?

**Comment by GeoffreyFrogeye** [comment]
English isn't my mother tongue either, so maybe I explained badly. I'll try to make simple sentences.

> please explain why do you want to support web browsers
I wanted to do a [graphical client in a web browser](http://i.imgur.com/vGLXdN0.png) for fun, but there were no in-browser client for agar.io. So I wanted to adapt your client to make it work in the browser. Your client is excellent work by the way :smile:.

I know, it doesn't make much sense since you can't connect to agar.io from any other site (due to browser restrictions; i had to use your repeater), but this is a little change and won't do much ; if you accept, obviously.

**Comment by pulviscriptor** [comment]
I am deeply sorry, but i cannot accept web browser support.
If you really want make web browser client, you can [do it](https://i.imgur.com/xTHE5Qw.png) with [browserify](http://browserify.org/) but as you already noticed you need to bypass [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) by using proxy/repeater and also change `BufferDataview` to `DataView`. 
And lets be honest, there is already one web [client](http://agar.io/).
Can you please PR `EventEmitter` and `client.color` part only?
Thank you.

**Comment by pulviscriptor** [comment]
If you do want to make browser client, i can change code to make it compatible with browserify without need to change `BufferDataview` to `DataView` every time. 
Tell me if you do.

**Comment by GeoffreyFrogeye** [comment]
No problem at all, it's your project :wink:.
Anyway, this web client is mostly done for fun, so it's not much of an issue. I planned to release it with `agario-client` as a dependency, so I could benefit from your upgrades.
If you could make the code compatible with browserify, that would be great, but if you don't want to, don't do it.

**Comment by pulviscriptor** [comment]
I fixed browserify, but instructions are little complicated.

If you will move your JS code from `.html` file to `.js` where you will have `var Client = require('/path/to/agario-client.js')` it will be little easier. For now you need to do:

Create `b-loader.js` with code:

    window.Client = require('/home/username/work/agario-client/agario-client.js');

This little hack will make `Client` accessible in your `.html` file.

Then do 

	browserify b-loader.js -o b-client.js

Then replace in your `.html` file

	<script src="agario-client.js"></script>

with

	<script src="b-client.js"></script>

And [here](https://i.imgur.com/NrUVnAI.png) you go.

Just run browserify when you update agario-client.
So now you can run your own repository and keep mine lib just as dependence.
Also your client is pretty cool, i like it.

**Comment by GeoffreyFrogeye** [comment]
Thanks! I had some issues understanding browserify so this little tutorial is just what I needed!

So I created [my own repo](https://github.com/GeoffreyFrogeye/agario-webclient) and everything works fine! But how did you manage not to overwrite `window.WebSocket`? I did [a little trick](https://github.com/GeoffreyFrogeye/agario-webclient/commit/48397199c55780b15dd187505f388422a52c82a4#diff-b67911656ef5d18c4ae36cb6741b7965R3), but this isn't the right way to go I think.

> Also your client is pretty cool, i like it.

Thanks, but it wouldn't be that cool without yours :smile:.

**Comment by pulviscriptor** [comment]
> how did you manage not to overwrite window.WebSocket

If I correctly understood you, you do not need to change `var WebSocket`. [ws lib](https://github.com/websockets/ws) is compatible with browserify as you can see in [README.md](https://github.com/websockets/ws#browserify-users)

**Comment by GeoffreyFrogeye** [comment]
I forgot to install `ws` via npm, that's why browserify wouldn't find it... Thanks!

**Pull request closed without merging**
