### PR TITLE
Fixes #129

### LINKED ISSUE #129: Facebook Bots patched!!
everything works normal but with no facebook mass... so its like 10 mass bots... but its strange that all my tokens work.... maybe we have to get some other sort than datr c_user or xs cookies

### PR DESCRIPTION
**Pull request by Cr4xy**

### CODE REVIEW

**Comment by hassanila97** [comment]
Thx bro @Cr4xy :+1:

**Comment by PcWars** [comment]
WTF ?

**Comment by hassanila97** [comment]
@PcWars WTF what??

**Comment by SrNicolas** [comment]
I think init key changed again

**Comment by MinersMC** [comment]
i guees nice

**Comment by sandor111** [comment]
How can i get my bots work again with this update?

**Comment by henopied** [comment]
A few things that may help get this pr excepted is if you could fix your indentation and use more descriptive commit titles.

**Comment by hassanila97** [comment]
@henopied Its already indented. He can't indent it any better

**Comment by henopied** [comment]
@hassanila97 He over indented :P

**Comment by Cr4xy** [comment]
@henopied No G+, i think you need to change the last byte before the token to a 2 to do do that, but im not sure.

**Comment by hassanila97** [comment]
Yes @Cr4xy but it works only when you know how to get G+ token.

**Comment by boboftw** [comment]
Facebook bots are not working again.. can someone repair the fb bots again? Thanks...

**Comment by philw1508** [comment]
its the problem with cookies... 2 days ago i recieved 1500.. now only 10 are working... fuck moneyclip

**Comment by henopied** [comment]
@Cr4xy you may want to figure that out as pulviscriptor had support for G+ if you at least had the token.

**Comment by pulviscriptor** [comment]
Tested, it works. Thank you very much!
Will update npm package in about 30mins.

**Comment by pulviscriptor** [comment]
Hmmmm, guys. Is it broke google+ tokens support? I don't see `auth_provider` variable used in that fix, or agar don't need `auth_provider` variable anymore?
Did anybody tested it with google+? I don't have tokens to test.

**Pull request merged**
