### PR TITLE
Corrected misspellings.

### PR DESCRIPTION
**Pull request by DRSDavidSoft**
Some words were also missing.

### CODE REVIEW

**Comment by pulviscriptor** [comment]
Thank you! 
Will update npm package when will be changing version.

**Comment by DRSDavidSoft** [comment]
I can work on the documentation, and sometimes improve the scripting if you give me write access :)

**Comment by pulviscriptor** [comment]
PR way is okay too.

**Comment by DRSDavidSoft** [comment]
Ok, I added more edits (two PRs to be exact)

**Pull request merged**
