### PR TITLE
Score support

### PR DESCRIPTION
**Pull request by GeoffreyFrogeye**
100% faithful.

### CODE REVIEW

**Comment by pulviscriptor** [comment]
Hi.

I am so sorry, but I have few complains again.
It's absolutely not your fault, it's just my vision of how I want code to look. If you will allow me to fix them by myself, I can do it.

First of all, please don't use EventEmitter inside lib. I made it for end user and if user will do `client.removeAllListeners()` that will break your code. And user is allowed to do that.

And i have complains about code style and variables names and etc. And again it's not you, it's problem in me.
Can i change your fork (if GitHub will allow do that) and then you will PR it? Are you okay with that?

**Comment by GeoffreyFrogeye** [comment]
I'm totally okay with that. I tried to mimic your code the best I could, but I clearly missed things. I'll see what I could have done better.
And yes, GitHub allows that, just clone my `score` branch to a `scorePulvi` branch at yours, then commit. After that submit a PR from `scorePulvi` to my `score`; ill accept it, your commit will get in this PR and then you'll can merge it. Or just merge this PR and immediately merge `scorePulvi` to `master`.

**Comment by pulviscriptor** [comment]
Okay, I tried to find out the correct way, but i just end up with merging your fork locally and then pushing it with my commits to GitHub. Looks like it works.

**Comment by GeoffreyFrogeye** [comment]
No worries, both method ends the same. 
I took account of the changes you did. 
Thanks for credits!

**Pull request merged**
